Task 5
makar-pelogeiko/formal-lang-course pull request #6
Opened 2021-10-13 20:48 UTC by makar-pelogeiko

# Задача 5. Экспериментальное исследование алгоритмов для регулярных запросов

* **Мягкий дедлайн**: 06.10.2021, 23:59
* **Жёсткий дедлайн**: 13.10.2021, 23:59
* Полный балл: 11

## Задача

Задача посвящена анализу производительности различных реализаций алгоритма решения задачи достижимости между всеми парами вершин с регулярными ограничениями через тензорное произведение.

Решение данной задачи оформляется как Python notebook на [Google colab](https://colab.research.google.com/). Для того, чтобы обеспечить возможность проверки, решение делается доступным по ссылке, ссылка добавляется в readme репозитория, в котором выполняются остальные задачи, делается реквест с этим изменением.

Решением является не просто код, но отчёт об экспериментальном исследовании, который должен являться связанным текстом и содержать (как минимум) следующие разделы:
- Постановка задачи
- Выбор и описание исследуемых решений
- Описание набора данных для экспериментов
  - Графы
  - Запросы
- Описание эксперимента
  - Оборудование
  - Что и как замерялось
- Результаты экспериментов
  - Графики, таблицы
- Анализ результатов экспериментов
  - Какой алгоритм и в каких случаях лучше? Почему?

- [x] Используя [pyCuBool](https://pypi.org/project/pycubool/) реализовать алгоритм пересечения двух конечных автоматов через тензорное произведение. Аналогично тому, как это было сделано в предыдущей домашней работе. Лучше сразу предусмотреть общий интерфейс функций, чтобы было проще ставить эксперименты.
- [x] Подключить решение из предыдущей работы.
- [x] Сформировать набор данных.
  - [x] Выбрать все графы из раздела [RDF](https://jetbrains-research.github.io/CFPQ_Data/dataset/RDF.html).
  - [x] Используя функцию из первой домашней работы узнать метки рёбер графов и на основе этой информации сформулировать не менее четырёх различных запросов к каждому графу. Требования к запросам:
      - Запросы ко всем графам должны следовать некоторому общему шаблону. Например, если есть графы ```g1``` и ```g2``` с различными наборами меток, то ожидается, что запросы к ним будут выглядеть, например, так:
        - ```g1```:
          - ```(l1 | l2)* l3```
          - ```(l3 | l4)+ l1*```
          - ```l1 l2 l3 (l4|l1)*```
        - ```g2```:
          - ```(m1 | m3)* m2```
          - ```(m1 | m3)+ m2*```
          - ```m1 m2 m3 (m3|m1)*```
      - В запросах должны использоваться все общепринятые конструкции регулярных выражений  (замыкание, конкатенация, альтернатива). То есть хотя бы в одном запросе к каждому графу должна быть каждая из этих конструкций.
- [x] С использованием сформированного набора данных провести сравнение производительности алгоритма, основанного на тензорном произведении, реализованного с использованием двух библиотек
  - sciPy (предыдущая работа)
  - pyCuBool (первый пункт этой работы)
- [x] Оформить результаты экспериментов
- [x] Провести анализ результатов
- [x] Сделать notebook доступным по ссылке (не забыть проверить, что выданы пава на комментирование)

2021-10-14 14:20 UTC, EgorOrachyov commented
А где ссылочка на colab ноутбук, или я что-то пропустил?

2021-10-17 18:52 UTC, EgorOrachyov requested changes
* см комментарий в ноутбуке

2022-01-21 18:21 UTC, makar-pelogeiko commented
> 
Доработал
 
`request_number` - отвечает за количество запросов: 10 - к маленьким графам и 3 к большим.
Вычисление среднего времени и среднеквадратичного отклонения добавлено в функции `rpq_time_test`

2022-01-23 16:08 UTC, EgorOrachyov requested changes

2022-01-23 16:08 UTC, EgorOrachyov commented on tests/test_interpreter.py
> -import pytest
**BRANCH FIX** Почему эти файлы удалены? Аккуратно вмерджить main в эту ветку, эти тесты в мастере должны остаться.

2022-01-23 16:08 UTC, EgorOrachyov commented on tests/test_parser.py
> -import pytest
**BRANCH FIX** Почему эти файлы удалены? Аккуратно вмерджить main в эту ветку, эти тесты в мастере должны остаться.

2022-01-23 16:08 UTC, EgorOrachyov commented on tests/test_parser_to_dot.py
> -import pytest
**BRANCH FIX** Почему эти файлы удалены? Аккуратно вмерджить main в эту ветку, эти тесты в мастере должны остаться.

2022-01-23 16:15 UTC, makar-pelogeiko commented on tests/test_parser_to_dot.py
> -import pytest
Изначально убрал их, чтоб не мешали при работе с этой веткой в в google colab. Вернул их и в эту ветку тоже

2022-01-23 16:52 UTC, EgorOrachyov approved these changes

2022-01-24 11:46 UTC, merged